version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    timezone: America/Costa_Rica
  open-pull-requests-limit: 10
  reviewers:
  - jsdanielh
  assignees:
  - jsdanielh
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    timezone: America/Costa_Rica
  open-pull-requests-limit: 10
  reviewers:
  - jsdanielh
  assignees:
  - jsdanielh
